name: "buildscanandsign"

on:
   workflow_call:
     inputs:
      dockerfilepath:
        description: The path of dockerfile 
        type: string
        required: false
        default: '.'

env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME:  '${{ github.event.repository.name }}'
  GAR_NAME: 'asia-south1-docker.pkg.dev'
  GAR_REPO_NAME: 'artifact-scanning-repo'
  tag: 'default'
  TAG_VERSION: 'default'
  workflow_name: 'gcp-invalid'
  IMAGE_NAME_WITH_TAG: 'default:default'
  PAC_ACTION: 'continue'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      actions: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Docker image
        id: docker-build
        run: |
              echo "Build in progress"
              pwd
              ls -lart
              echo "Docker file is in ${{inputs.dockerfilepath}}"
              export GOOGLE_CLOUD_PROJECT="jmc-devsecops"
              export IMAGE_ID=${GAR_NAME}/${GOOGLE_CLOUD_PROJECT}/${GAR_REPO_NAME}/$IMAGE_NAME
              docker build . --file ${{inputs.dockerfilepath}}/Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
      - name: docker-push
        id: docker-push
        run: |
            docker ls
            export IMAGE_ID=${GAR_NAME}/${GOOGLE_CLOUD_PROJECT}/${GAR_REPO_NAME}/$IMAGE_NAME
            docker push $IMAGE_ID:${GITHUB_RUN_ID}